In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#MovieLens Data

In [ ]:
import pandas as pd
import numpy as np
import os
from scipy.sparse.linalg import svds

data_path = '/content/drive/MyDrive/AI_P2'
movies_filename = '/content/drive/MyDrive/AI_P2/movie.csv'
ratings_filename = '/content/drive/MyDrive/AI_P2/rating.csv'

df_movies = pd.read_csv(
    os.path.join(data_path, movies_filename),
    usecols=['movieId', 'title'],
    dtype={'movieId': 'int32', 'title': 'str'})

df_ratings = pd.read_csv(
    os.path.join(data_path, ratings_filename),
    usecols=['userId', 'movieId', 'rating'],
    dtype={'userId': 'int32', 'movieId': 'int32', 'rating': 'float32'})

In [ ]:
df_ratings.shape

(20000263, 3)

In [ ]:
df_ratings.head()

userId  movieId  rating
0       1        2     3.5
1       1       29     3.5
2       1       32     3.5
3       1       47     3.5
4       1       50     3.5

In [ ]:
df_movies.head()

movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

# Singular Value Decomposition

In [ ]:
df_ratings=df_ratings[:2000000] #take the first 2 million ratings
#create MxN matrix
df_movie_features = df_ratings.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(0) #NaN values are filled with 0.0

In [ ]:
df_movie_features.head()

movieId  1       2       3       4       ...  130512  130642  130644  130768
userId                                   ...                                
1           0.0     3.5     0.0     0.0  ...     0.0     0.0     0.0     0.0
2           0.0     0.0     4.0     0.0  ...     0.0     0.0     0.0     0.0
3           4.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
4           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
5           0.0     3.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[5 rows x 16715 columns]

In [ ]:
A = df_movie_features.to_numpy()
user_ratings_mean = np.mean(A, axis = 1)
centered = A - user_ratings_mean.reshape(-1, 1)

## **A = USV^T**

In [ ]:
# 
U, singular_values, V_T = svds(centered, k = 50)

In [ ]:
U

array([[ 0.01068878, -0.00921775, -0.01028504, ..., -0.00232665,
        -0.0053511 , -0.00880595],
       [ 0.00369479, -0.00426444, -0.00194045, ..., -0.00081597,
         0.00162059, -0.00313261],
       [-0.00910756,  0.00383238, -0.0003485 , ..., -0.01183656,
         0.00561438, -0.01114692],
       ...,
       [ 0.03344654,  0.00814001, -0.0064223 , ...,  0.01775382,
        -0.03140629, -0.01667692],
       [ 0.00351431,  0.00217941, -0.00426903, ...,  0.00020301,
        -0.00289936, -0.00299958],
       [-0.00355733, -0.00207085, -0.00279444, ...,  0.0006775 ,
        -0.0015722 , -0.000545  ]], dtype=float32)

In [ ]:
V_T

array([[-9.4745994e-02,  3.5969794e-02,  3.8766559e-02, ...,
        -6.9792346e-05,  3.9069750e-04, -3.2128239e-05],
       [ 2.1622902e-01,  1.0363584e-02,  9.1373045e-03, ...,
        -4.7166197e-04, -5.9748051e-04, -6.0774043e-04],
       [ 5.0549783e-02,  1.3126427e-02,  7.9947263e-03, ...,
        -1.2581376e-03, -9.9417928e-04, -9.9782378e-04],
       ...,
       [ 4.4677924e-02,  4.9580220e-02,  1.3000269e-02, ...,
         1.0197614e-03,  1.1681132e-03,  1.0931707e-03],
       [ 3.0714178e-02,  2.7605044e-02,  2.7576867e-02, ...,
         3.6482033e-04,  3.1626856e-04,  4.1824370e-04],
       [-8.1684217e-02, -3.4953836e-02, -1.3232198e-02, ...,
         2.6181366e-03,  2.6274004e-03,  2.6499394e-03]], dtype=float32)

In [ ]:
singular_values = np.diag(singular_values)

In [ ]:
singular_values

array([[ 193.32753,    0.     ,    0.     , ...,    0.     ,    0.     ,
           0.     ],
       [   0.     ,  195.30287,    0.     , ...,    0.     ,    0.     ,
           0.     ],
       [   0.     ,    0.     ,  196.64787, ...,    0.     ,    0.     ,
           0.     ],
       ...,
       [   0.     ,    0.     ,    0.     , ...,  864.34503,    0.     ,
           0.     ],
       [   0.     ,    0.     ,    0.     , ...,    0.     ,  913.46124,
           0.     ],
       [   0.     ,    0.     ,    0.     , ...,    0.     ,    0.     ,
        2219.4346 ]], dtype=float32)

In [ ]:
# predict movie ratings
predicted_ratings = np.dot(np.dot(U, singular_values), V_T) + user_ratings_mean.reshape(-1, 1)

In [ ]:
preds_df = pd.DataFrame(predicted_ratings, columns = df_movie_features.columns)
preds_df.head()

movieId    1         2         3       ...    130642    130644    130768
0       -1.032371  0.816785  0.065364  ... -0.006603 -0.001093 -0.002193
1        0.878409  0.018589  0.350089  ...  0.001166 -0.000476  0.000287
2        2.004502  0.853211 -0.124892  ... -0.001381 -0.001391  0.000514
3       -0.730041  0.575875  0.316375  ...  0.001607  0.002382  0.001786
4        1.487823  1.324306  1.370971  ...  0.001492  0.001601  0.001771

[5 rows x 16715 columns]

# Recommendations

In [ ]:
def recommend_movies(preds_df, userId, movies_df, ratings_df, n=5):
    
    # Get Predictions
    user_row = userId - 1 #account for 0 index
    user_predictions = preds_df.iloc[user_row].sort_values(ascending=False) 
    # Merge Movie Titles
    user_data = ratings_df[ratings_df.userId == (userId)]
    watched = (user_data.merge(movies_df, how = 'left', on = 'movieId').
                     sort_values(['rating'], ascending=False))
    # Recommend
    recommendations = (movies_df[~movies_df['movieId'].isin(watched['movieId'])]).merge(pd.DataFrame(user_predictions).reset_index(), how = 'left', on= 'movieId'
                                                                                ).rename(columns = {user_row: 'Predictions'}
                                                                                ).sort_values('Predictions', ascending = False
                                                                                ).iloc[:n, :-1]
                      

    return watched, recommendations

In [ ]:
watched, recommendations = recommend_movies(preds_df, 3000, df_movies, df_ratings, 15)

In [ ]:
# movies the user has watched an rated
watched.head(10)

userId  movieId  rating                                              title
82    3000     2115     5.0        Indiana Jones and the Temple of Doom (1984)
87    3000     2193     5.0                                      Willow (1988)
39    3000     1193     5.0             One Flew Over the Cuckoo's Nest (1975)
41    3000     1198     5.0  Raiders of the Lost Ark (Indiana Jones and the...
42    3000     1201     5.0  Good, the Bad and the Ugly, The (Buono, il bru...
48    3000     1235     5.0                            Harold and Maude (1971)
49    3000     1246     5.0                          Dead Poets Society (1989)
52    3000     1283     5.0                                   High Noon (1952)
53    3000     1291     5.0          Indiana Jones and the Last Crusade (1989)
54    3000     1293     5.0                                      Gandhi (1982)

In [ ]:
# top n recommendations based on user ratings
recommendations

movieId                              title
1801     1961                    Rain Man (1988)
1041     1097  E.T. the Extra-Terrestrial (1982)
873       919           Wizard of Oz, The (1939)
1191     1270          Back to the Future (1985)
338       356                Forrest Gump (1994)
556       587                       Ghost (1990)
2608     2797                         Big (1988)
138       150                   Apollo 13 (1995)
1180     1259                 Stand by Me (1986)
2218     2396         Shakespeare in Love (1998)
1137     1207       To Kill a Mockingbird (1962)
1186     1265               Groundhog Day (1993)
2727     2918    Ferris Bueller's Day Off (1986)
563       595        Beauty and the Beast (1991)
1024     1079        Fish Called Wanda, A (1988)

# Correlation



In [ ]:
#matrix = df_movie_features
df_movies['title'] = df_movies['title'].apply(lambda old_string: old_string.strip())
df = pd.merge(df_movies, df_ratings, on='movieId', how='inner')
df.head()

movieId             title  userId  rating
0        1  Toy Story (1995)       3     4.0
1        1  Toy Story (1995)       6     5.0
2        1  Toy Story (1995)       8     4.0
3        1  Toy Story (1995)      10     4.0
4        1  Toy Story (1995)      11     4.5

In [ ]:
#create sparse MxN matrix
search_matrix = df.pivot_table(
    index='userId',
    columns='title',
    values='rating'
).fillna(0) #NaN values are filled with 0.0

## Check Data

In [ ]:
#creating average mean rating of movie_title
ratings = pd.DataFrame(df.groupby('title')['rating'].mean())
#adding number of ratings on movie
ratings['number_of_ratings'] = df.groupby('title')['rating'].count()
ratings = ratings.reset_index()
ratings.head()

title    rating  number_of_ratings
0                       $ (Dollars) (1971)  2.500000                  1
1                          $5 a Day (2008)  2.642857                  7
2                             $9.99 (2008)  4.250000                  2
3                               '71 (2014)  3.200000                  5
4  'Hellboy': The Seeds of Creation (2004)  3.000000                  5

In [ ]:
#most rated movie
ratings['title'] = ratings['title'].apply(lambda old_string: old_string.strip())
ratings.sort_values('number_of_ratings', ascending=False).head(10)

title    rating  number_of_ratings
11893                        Pulp Fiction (1994)  4.166567               6688
5527                         Forrest Gump (1994)  4.043264               6599
13301           Silence of the Lambs, The (1991)  4.188796               6221
13155           Shawshank Redemption, The (1994)  4.456364               6199
8062                        Jurassic Park (1993)  3.671210               5943
13880  Star Wars: Episode IV - A New Hope (1977)  4.198512               5443
2241                           Braveheart (1995)  4.038469               5329
14576          Terminator 2: Judgment Day (1991)  3.949971               5267
9588                          Matrix, The (1999)  4.186778               5105
12863                    Schindler's List (1993)  4.306500               4969

##Making Recommendation Similar to "Input"

In [ ]:
#Making Recommendation by input
input='Rain Man (1988)'
input_rating = search_matrix[input]


In [ ]:
#Finding similar movie
similar_to_input = search_matrix.corrwith(input_rating).sort_values(ascending=False)
similar_to_input.head()

title
Rain Man (1988)              1.000000
Good Will Hunting (1997)     0.441145
Dead Poets Society (1989)    0.419234
Truman Show, The (1998)      0.407984
As Good as It Gets (1997)    0.396372
dtype: float64

##Threshold for min num of ratings

In [ ]:
#create dataframe
sim_input = pd.DataFrame(similar_to_input, columns=['Correlation'])
sim_input = pd.merge(sim_input, df_movies, on='title', how='left')
sim_input.dropna(inplace=True)
sim_input.head()

title  Correlation  movieId
0            Rain Man (1988)     1.000000     1961
1   Good Will Hunting (1997)     0.441145     1704
2  Dead Poets Society (1989)     0.419234     1246
3    Truman Show, The (1998)     0.407984     1682
4  As Good as It Gets (1997)     0.396372     1784

In [ ]:
#adding in ratings
# sim_input = sim_input.join(ratings['number_of_ratings'])
sim_input = pd.merge(sim_input, ratings, on='title', how='left')
sim_input.head()

title  Correlation  movieId    rating  number_of_ratings
0            Rain Man (1988)     1.000000     1961  3.880943               2419
1   Good Will Hunting (1997)     0.441145     1704  4.010462               2772
2  Dead Poets Society (1989)     0.419234     1246  3.887679               2021
3    Truman Show, The (1998)     0.407984     1682  3.828620               2369
4  As Good as It Gets (1997)     0.396372     1784  3.785780               2173

In [ ]:
sim_input[sim_input['number_of_ratings']>500].sort_values(by='Correlation',ascending=False).head(10)

title  ...  number_of_ratings
0                             Rain Man (1988)  ...               2419
1                    Good Will Hunting (1997)  ...               2772
2                   Dead Poets Society (1989)  ...               2021
3                     Truman Show, The (1998)  ...               2369
4                   As Good as It Gets (1997)  ...               2173
5         There's Something About Mary (1998)  ...               2462
6                                  Big (1988)  ...               1956
7           E.T. the Extra-Terrestrial (1982)  ...               3198
8             Ferris Bueller's Day Off (1986)  ...               2297
9  Ghostbusters (a.k.a. Ghost Busters) (1984)  ...               2983

[10 rows x 5 columns]